### ISSUE TITLE
Report: 相同固定 IP，多組電號會取得相同的 SESSION & CSRF

### ISSUE THREAD

**Issue by bluefoxlee** [tsunglung/TaiPowerFee#1]
台電應該是根據 IP 回應查詢，所以當使用固定 IP 進行查詢多組電號，會得到相同的 SESSION & CSRF
另如果設定不正確，整合不斷地要求資料，會導致該 IP 無法連線查詢（改連手機分享網路測試則恢復正常）

**Comment by tsunglung** [comment]
感謝 bluefox 大大指教！！

每次 Session 取得的 token 和 csrf 是可以查詢不同的電號。
台電網站目前的 session 的有效期大約 15 分鐘，所以，現在會每隔 15分鐘讀取台電網站，這樣的情況下，session 是不會過期。
Jason 有試過，每隔 10分鐘去讀取一次，持續二天都不會 session 或是被台電封鎖 ip 。
台電網站會檢查 csrf 及 token 是否正確和是否過期，如果過期或不正確的 csrf 和 token ，且還一直讀取台電網站，就會封鎖 ip 。
只要 csrf 和 token 過期了，目前設計是就不會去讀取台電網站，避免被封鎖 ip 。
但是，如果輸錯誤的 csrf 和 token ，我再檢查一下 code。
台電網站，沒有提供使用者申請 long term 的 token。不然，實在不想也沒意義，每 15分鐘就去讀取一次。
另外，二個實作，台水和北水，雖然也沒有 long term token，但它們的 session 沒有檢查機制，所以目前是 12小時，24小時，檢查一次。

**Comment by bluefoxlee** [comment]
> 感謝 bluefox 大大指教！！

恩啊＠＠ 為何叫我大大….大大是各位會寫 Code 造福人群的人
 
> 每次 Session 取得的 token 和 csrf 是可以查詢不同的電號。

學習了！忘了這招。明天來試試看

> 只要 csrf 和 token 過期了，目前設計是就不會去讀取台電網站，避免被封鎖 ip 。
> 但是，如果輸錯誤的 csrf 和 token ，我再檢查一下 code。

那我應該是放著不管 就被封鎖了 囧 （應該被當成攻擊了）
有可能增加設定查詢頻率選項嗎？畢竟電費更新頻率應該還好

> 台電網站，沒有提供使用者申請 long term 的 token。不然，實在不想也沒意義，每 15分鐘就去讀取一次。
> 另外，二個實作，台水和北水，雖然也沒有 long term token，但它們的 session 沒有檢查機制，所以目前是 12小時，24小時，檢查一次。

確實沒提供使用者Long term token….還挺不便
看到台電這個 Add-on、原來還有水費 add-on，大感恩！謝謝你們

**Comment by tsunglung** [comment]
> > 恩啊＠＠ 為何叫我大大….大大是各位會寫 Code 造福人群的人

 從小拜讀 BlueFox 大大的文章長大

> > 那我應該是放著不管 就被封鎖了 囧 （應該被當成攻擊了）
> > 有可能增加設定查詢頻率選項嗎？畢竟電費更新頻率應該還好
 
有想過這個選項，但沒有意義，要是使用者設定超過 15 分鐘，session 就會過期了。
 

> 確實沒提供使用者Long term token….還挺不便
> 看到台電這個 Add-on、原來還有水費 add-on，大感恩！謝謝你們

還有天然氣的，不過，只實作了一個。還有好幾家天然氣公司，無法一一加入。
大部分的天然氣公司網站都用同一個方法，所以，取值方式雷同.

**Comment by bluefoxlee** [comment]
> 從小拜讀 BlueFox 大大的文章長大

很意外亂寫的東西有人看（如果沒認錯人的話） Orz....
貼給好友，「從小」這幾個字讓他們笑翻了

> 有想過這個選項，但沒有意義，要是使用者設定超過 15 分鐘，session 就會過期了。

感謝說明。目前我的 IP 還是被封鎖中。尷尬。

> 還有天然氣的，不過，只實作了一個。還有好幾家天然氣公司，無法一一加入。
> 大部分的天然氣公司網站都用同一個方法，所以，取值方式雷同.

台電有提供了會員註冊查詢、不知道機制是否一樣。

如果公共費用都能夠導入追蹤就方便很多了。
之所以對於電費特別有興趣是，如同您一樣也搭架了 PZEM-004、想說可以追蹤比對。
Anyway...再次謝謝 add-on ^^ 您的相館也好久沒更新了

**Comment by tsunglung** [comment]
>
> 感謝說明。目前我的 IP 還是被封鎖中。尷尬。
> 

如果是撥接網路，不是固定 IP ，可以試著數據機重開。試試。如果是固定 IP，可能就得反應給台電網站了。


>
> 台電有提供了會員註冊查詢、不知道機制是否一樣。
> 

一樣 


> 如果公共費用都能夠導入追蹤就方便很多了。
> 之所以對於電費特別有興趣是，如同您一樣也搭架了 PZEM-004、想說可以追蹤比對。
> Anyway...再次謝謝 add-on ^^ 您的相館也好久沒更新了

之前有比對過，PZEM-004 的統計跟台電帳單，誤差範圍在 5%。
wordpress 前陣子有一篇文章是網關的，應該不會很久。

另 LINE 社群有幾個是討論智慧家庭的，歡迎大大加入討論。

**Comment by bluefoxlee** [comment]
> 如果是撥接網路，不是固定 IP ，可以試著數據機重開。試試。如果是固定 IP，可能就得反應給台電網站了。

因為有三處 HA，為了網域名方便、都是採用固定 IP。來發信給台電問問看了

> 之前有比對過，PZEM-004 的統計跟台電帳單，誤差範圍在 5%。
> wordpress 前陣子有一篇文章是網關的，應該不會很久。
> 
> 另 LINE 社群有幾個是討論智慧家庭的，歡迎大大加入討論。

5% 相當不錯耶、那來精進一下 HA 的統計呈現。
網關文也已經一月了 :P

方便請教大大，LINE 的 URL or QR 嗎？

**Comment by tsunglung** [comment]
固定 IP 不好用,

password: homekit
https://line.me/ti/g2/1wcYkUqCwW1sM1haK7J-OA?utm_source=invitation&utm_medium=link_copy&utm_campaign=default
或是
https://line.me/ti/g2/ALKu80qOmqZc6DpIkUTXQg?utm_source=invitation&utm_medium=link_copy&utm_campaign=default


https://line.me/ti/g2/LsZW-OOlswq1aytiQl1nmg?utm_source=invitation&utm_medium=link_copy&utm_campaign=default

還有一個是 Jason 開的社群. 在 dcard 那看的到.

都是開放性的社群, 歡迎加入.

**Comment by bluefoxlee** [comment]
> 固定 IP 不好用,

因為有三個地方的 Home Assistant、又不想用 Add-on 串在一起，管理方便只好這樣了。

> 都是開放性的社群, 歡迎加入.

已加入，謝謝您。好多群、有點反社群個性。還是比較喜歡討論區或者 Reddit 那樣的方式好追蹤（回答）問題，否則有些人的提問很容易被淹沒就.....消失了。

先關閉此 Issue（Question）。

**Comment by bluefoxlee** [comment]
Not an issue but a question and feedback.
